# Site settings
title: Structural Ecology
email: russell@njit.edu
description: Academic webpage of Dr. Gareth Russell at NJIT
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Gareth Russell<br/>
  Associate Professor of Ecology<br/>
  New Jersey Institute of Technology

location: >
  New Jersey Institute of Technology<br/>
  353 Martin Luther King Jr. Blvd<br/>
  Newark NJ 07102

contact: >
  <a href="mailto:russell@njit.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Gareth via email</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: people
  - name: research
  - name: publications
  - name: talks
  - name: software
  - name: teaching
  - name: blog

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Russell
  first_name: [Gareth]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
